version: '2'
services:
  data:
    container_name: dataonly
    build: ./setting/data
    volumes:
      - /var/lib/mysql
  mysql:
    container_name: mysql
    build: ./setting/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes_from:
      - data
    links:
      - data
  web:
    container_name: web
    build: ./setting/web
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    links:
      - "mysql"
